---
- name: Set BIG-IP admin password and enable iApps LX in GUI
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ SSH_KEY_PATH }}"
      transport: cli
      user: admin
      validate_certs: no
    commands: 
      - modify auth user admin password {{ ADMIN_PASSWORD }}
      - run /util bash -c "touch /var/config/rest/iapps/enable"
  delegate_to: localhost
